# Starter pipeline

trigger:
  batch: true
  branches:
    include:
      - master
pr:
  - master

variables:
  - group: symfony-docker
  - name: acrLogin
    value: 'docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword);'
  - name: envRun
    value: 'docker-compose -f symfony/docker/ci/docker-compose.yaml -p symfony-docker up;'
  - name: depInstall
    value: 'docker-compose -f symfony/docker/ci/docker-compose.yaml -p symfony-docker exec -T php sh -c "composer install --prefer-dist --no-ansi --optimize-autoloader --no-interaction --no-progress";'
  - name: prepare
    value: '$(acrLogin) $(envRun) $(depInstall)'
  - name: execute
    value: 'docker-compose -f symfony/docker/ci/docker-compose.yaml -p symfony-docker exec -T php sh -c'

jobs:
  - job: code_style
    displayName: Code style
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          $(prepare)
        displayName: 'Prepare environment'
      - bash: |
          $(execute) "bin/phpcs --no-colors -q"
        displayName: 'Code style'

  - job:
    displayName: PHPStan analysis
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          $(prepare)
        displayName: 'Prepare environment'
      - bash: |
          $(execute) "bin/phpstan analyse src --no-ansi --no-progress -c phpstan.neon"
        displayName: 'PHPStan Analysis'

  - job:
    displayName: PHPUnit tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          $(prepare)
        displayName: 'Prepare environment'
      - bash: |
          $(execute) "bin/phpunit --log-junit TEST-phpunit-junit.xml"
        displayName: 'PHPUnit tests'
      - task: PublishTestResults@2
        displayName: 'Publish results'
        inputs:
          testRunner: 'JUnit'
          testResultsFiles: '**/TEST-phpunit-junit.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
