version: '3.4'
x-symfony-common:
    &symfony-common-config
      APP_ENV: 'dev'
      APP_DEBUG: '1'
      APP_SECRET: '!ChangeMe!'
      DATABASE_URL: 'mysql://symfony:symfony@mysql:3306/symfony'

x-mysql-common:
    &mysql-common-config
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      
services:
    php:
        image: symfony.azurecr.io/php:ci
        container_name: php.ci
        depends_on:
            - mysql
        # Comment out these volumes in production
        volumes:
            - ./symfony:/srv/symfony:rw,cached
        # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
        environment:
            << : *symfony-common-config
            << : *mysql-common-config

    nginx:
        image: symfony.azurecr.io/nginx:ci
        container_name: symfony.ci
        depends_on:
            - php
        ports:
            - '8080:80'
        volumes:
            - ./symfony/public:/srv/symfony/public:ro

    mysql:
      container_name: mysql.ci
      image: mysql/mysql-server:5.7
      command: ["--default-authentication-plugin=mysql_native_password"]
      ports:
        - '8036:3306'
      volumes:
        - ./var/mysql:/var/lib/mysql
      environment:
        << : *mysql-common-config

    h2-proxy:
        # Don't use this proxy in prod
        image: symfony.azurecr.io/h2-proxy:ci
        container_name: h2-proxy.ci
        depends_on:
          - nginx
        ports:
          - 80:80
          - 443:443
